//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaudiaVedantaPublications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaudiaVedantaPublications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразовать к шрифту {0}.
        /// </summary>
        internal static string ConvertToFont_Label {
            get {
                return ResourceManager.GetString("ConvertToFont_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразовать к обычному шрифту.
        /// </summary>
        internal static string ConvertToNormalFont_Label {
            get {
                return ResourceManager.GetString("ConvertToNormalFont_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразовать к обычному шрифту.
        /// </summary>
        internal static string ConvertToNormalFont_Screentip {
            get {
                return ResourceManager.GetString("ConvertToNormalFont_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привести текст к Юникоду, чтобы он корректно отображался во всех стандартных шрифтах..
        /// </summary>
        internal static string ConvertToNormalFont_Supertip {
            get {
                return ResourceManager.GetString("ConvertToNormalFont_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привести к рабочему шрифту.
        /// </summary>
        internal static string ConvertToOperationalFont_Screentip {
            get {
                return ResourceManager.GetString("ConvertToOperationalFont_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразовать текст так, чтобы он корректно отображался в текущем рабочем шрифте..
        /// </summary>
        internal static string ConvertToOperationalFont_Supertip {
            get {
                return ResourceManager.GetString("ConvertToOperationalFont_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кириллические шрифты.
        /// </summary>
        internal static string CyrillicFontsSeparator_Title {
            get {
                return ResourceManager.GetString("CyrillicFontsSeparator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кириллические опции.
        /// </summary>
        internal static string CyrillicOptionsToggleButton_Label {
            get {
                return ResourceManager.GetString("CyrillicOptionsToggleButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Латинские шрифты.
        /// </summary>
        internal static string RomanFontsSeparator_Title {
            get {
                return ResourceManager.GetString("RomanFontsSeparator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsGroup_Label {
            get {
                return ResourceManager.GetString("SettingsGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsMenu_Label {
            get {
                return ResourceManager.GetString("SettingsMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GVP.
        /// </summary>
        internal static string TabGVP_Label {
            get {
                return ResourceManager.GetString("TabGVP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to देवनागरी → Devanāgarī.
        /// </summary>
        internal static string TransliterateDevanagari_Label {
            get {
                return ResourceManager.GetString("TransliterateDevanagari_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация из Деванагари в Латиницу.
        /// </summary>
        internal static string TransliterateDevanagari_Screentip {
            get {
                return ResourceManager.GetString("TransliterateDevanagari_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерировать Деванагари в Латиницу..
        /// </summary>
        internal static string TransliterateDevanagari_Supertip {
            get {
                return ResourceManager.GetString("TransliterateDevanagari_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devanāgarī → Девана̄гарӣ.
        /// </summary>
        internal static string TransliterateRoman_Label {
            get {
                return ResourceManager.GetString("TransliterateRoman_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация Латиницы в Кириллицу..
        /// </summary>
        internal static string TransliterateRoman_Screentip {
            get {
                return ResourceManager.GetString("TransliterateRoman_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерировать Латиницу в Кириллицу..
        /// </summary>
        internal static string TransliterateRoman_Supertip {
            get {
                return ResourceManager.GetString("TransliterateRoman_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация.
        /// </summary>
        internal static string TransliterationGroup_Label {
            get {
                return ResourceManager.GetString("TransliterationGroup_Label", resourceCulture);
            }
        }
    }
}
