//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaudiaVedantaPublications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaudiaVedantaPublications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразовать.
        /// </summary>
        internal static string ButtonProcess_Label {
            get {
                return ResourceManager.GetString("ButtonProcess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить отмеченные преобразования.
        /// </summary>
        internal static string ButtonProcess_Screentip {
            get {
                return ResourceManager.GetString("ButtonProcess_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразование выделенного текста в соответствии с выбранными настройками. Если выбран особый шрифт, то символы будут преобразованы так, чтобы они корректно отображались в этом шрифте. Первоначально прозводится преобразование текста из нестандартных кодировок в Юникод..
        /// </summary>
        internal static string ButtonProcess_Supertip {
            get {
                return ResourceManager.GetString("ButtonProcess_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из Деванагари в Латиницу.
        /// </summary>
        internal static string CheckBoxDevanagari_Label {
            get {
                return ResourceManager.GetString("CheckBoxDevanagari_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация Деванагари.
        /// </summary>
        internal static string CheckBoxDevanagari_Screentip {
            get {
                return ResourceManager.GetString("CheckBoxDevanagari_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнять транслитерацию деванагари в латиницу..
        /// </summary>
        internal static string CheckBoxDevanagari_Supertip {
            get {
                return ResourceManager.GetString("CheckBoxDevanagari_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из Латиницы в Кириллицу.
        /// </summary>
        internal static string CheckBoxRoman_Label {
            get {
                return ResourceManager.GetString("CheckBoxRoman_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация Латиницы.
        /// </summary>
        internal static string CheckBoxRoman_Screentip {
            get {
                return ResourceManager.GetString("CheckBoxRoman_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнять транслитерацию Латиницы в Кириллицу..
        /// </summary>
        internal static string CheckBoxRoman_Supertip {
            get {
                return ResourceManager.GetString("CheckBoxRoman_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string DropDownFont_Label {
            get {
                return ResourceManager.GetString("DropDownFont_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нестандартный шрифт для кодирования текста.
        /// </summary>
        internal static string DropDownFont_Screentip {
            get {
                return ResourceManager.GetString("DropDownFont_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В конце преобразования текст кодируется так, чтобы отображаться корректно в выбранном нестандартном шрифте..
        /// </summary>
        internal static string DropDownFont_Supertip {
            get {
                return ResourceManager.GetString("DropDownFont_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслитерация.
        /// </summary>
        internal static string GroupTransliteration_Label {
            get {
                return ResourceManager.GetString("GroupTransliteration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string MenuSettings_Label {
            get {
                return ResourceManager.GetString("MenuSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный.
        /// </summary>
        internal static string NormalFontName {
            get {
                return ResourceManager.GetString("NormalFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GVP.
        /// </summary>
        internal static string TabGVP_Label {
            get {
                return ResourceManager.GetString("TabGVP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русские опции.
        /// </summary>
        internal static string ToggleRussian_Label {
            get {
                return ResourceManager.GetString("ToggleRussian_Label", resourceCulture);
            }
        }
    }
}
