//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VedicEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VedicEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x00C4;&quot; to=&quot;Ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E4;&quot; to=&quot;ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00CE;&quot; to=&quot;Ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E3;&quot; to=&quot;ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C3;&quot; to=&quot;ā̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D2;&quot; to=&quot;Ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F2;&quot; to=&quot;ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E1;&quot; to=&quot;ē&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00FD;&quot; to=&quot;ẽ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C1;&quot; to=&quot;ē̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D9;&quot; to=&quot;Ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F9;&quot; to=&quot;ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Amita_Times {
            get {
                return ResourceManager.GetString("Amita Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x0406;&quot; to=&quot;А̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x2026;&quot; to=&quot;а̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0402;&quot; to=&quot;а̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0403;&quot; to=&quot;а̄̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0456;&quot; to=&quot;Д̣&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x2020;&quot; to=&quot;д̣&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0407;&quot; to=&quot;е̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x03BC;&quot; to=&quot;Ӣ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x2021;&quot; to=&quot;ӣ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x045C;&quot; to=&quot;и̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x045B;&quot; to=&quot;ӣ̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x2030;&quot; to=&quot;л̐&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Amita_Times_Cyr {
            get {
                return ResourceManager.GetString("Amita Times Cyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x00C4;&quot; to=&quot;Ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E4;&quot; to=&quot;ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E3;&quot; to=&quot;ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D2;&quot; to=&quot;Ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F2;&quot; to=&quot;ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D9;&quot; to=&quot;Ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F9;&quot; to=&quot;ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C9;&quot; to=&quot;Ī&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E9;&quot; to=&quot;ī&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00FB;&quot; to=&quot;l̐&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00FF;&quot; to=&quot;ḷ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C0;&quot; to=&quot;Ṁ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Balaram {
            get {
                return ResourceManager.GetString("Balaram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x00A1;&quot; to=&quot;ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00A2;&quot; to=&quot;ī&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00A3;&quot; to=&quot;ū&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00A4;&quot; to=&quot;ṛ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00A5;&quot; to=&quot;ṝ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00A7;&quot; to=&quot;ṙ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00AB;&quot; to=&quot;ḻ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00AC;&quot; to=&quot;ḻ̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00AE;&quot; to=&quot;ē&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00B0;&quot; to=&quot;ō&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00B4;&quot; to=&quot;ṅ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00B5;&quot; to=&quot;ñ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DVRoman_TTSurekh {
            get {
                return ResourceManager.GetString("DVRoman-TTSurekh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечный шрифт.
        /// </summary>
        internal static string EndFont {
            get {
                return ResourceManager.GetString("EndFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный шрифт.
        /// </summary>
        internal static string InitialFont {
            get {
                return ResourceManager.GetString("InitialFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;a&quot; to=&quot;а&quot; /&gt;
        ///  &lt;entry from=&quot;A&quot; to=&quot;А&quot; /&gt;
        ///  &lt;entry from=&quot;ā&quot; to=&quot;а̄&quot; /&gt;
        ///  &lt;entry from=&quot;Ā&quot; to=&quot;А̄&quot; /&gt;
        ///  &lt;entry from=&quot;ã&quot; to=&quot;а̃&quot; /&gt;
        ///  &lt;entry from=&quot;Ã&quot; to=&quot;А̃&quot; /&gt;
        ///  &lt;entry from=&quot;ā̃&quot; to=&quot;а̄̃&quot; /&gt;
        ///  &lt;entry from=&quot;Ā̃&quot; to=&quot;А̄̃&quot; /&gt;
        ///  &lt;entry from=&quot;b&quot; to=&quot;б&quot; /&gt;
        ///  &lt;entry from=&quot;B&quot; to=&quot;Б&quot; /&gt;
        ///  &lt;entry from=&quot;c&quot; to=&quot;ч&quot; /&gt;
        ///  &lt;entry from=&quot;C&quot; to=&quot;Ч&quot; /&gt;
        ///  &lt;entry from=&quot;d&quot; to=&quot;д&quot; /&gt;
        ///  &lt;entry from=&quot;D&quot; to=&quot;Д&quot; /&gt;
        ///  &lt;entry from=&quot;ḍ&quot; to=&quot;д̣&quot; /&gt;
        ///  &lt;entry from=&quot;Ḍ&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Lat2Cyr {
            get {
                return ResourceManager.GetString("Lat2Cyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x00C4;&quot; to=&quot;Ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E4;&quot; to=&quot;ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00CE;&quot; to=&quot;Ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E3;&quot; to=&quot;ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C3;&quot; to=&quot;ā̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D2;&quot; to=&quot;Ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F2;&quot; to=&quot;ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E1;&quot; to=&quot;ē&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D7;&quot; to=&quot;ẽ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C1;&quot; to=&quot;ē̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D9;&quot; to=&quot;Ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F9;&quot; to=&quot;ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Rama_Garamond_Plus {
            get {
                return ResourceManager.GetString("Rama Garamond Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///  &lt;entry from=&quot;&amp;#x00C4;&quot; to=&quot;Ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E4;&quot; to=&quot;ā&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E3;&quot; to=&quot;ã&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D2;&quot; to=&quot;Ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F2;&quot; to=&quot;ḍ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00D9;&quot; to=&quot;Ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00F9;&quot; to=&quot;ḥ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C9;&quot; to=&quot;Ī&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00E9;&quot; to=&quot;ī&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00FB;&quot; to=&quot;l̐&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00FF;&quot; to=&quot;ḷ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00C0;&quot; to=&quot;Ṁ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x00 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ScaSeries {
            get {
                return ResourceManager.GetString("ScaSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map fontName=&quot;ThamesM&quot;&gt;
        ///  &lt;entry from=&quot;&amp;#x0066;&quot; to=&quot;а̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0046;&quot; to=&quot;А̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0061;&quot; to=&quot;а̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0041;&quot; to=&quot;а̄̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x006C;&quot; to=&quot;д̣&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x004C;&quot; to=&quot;Д̣&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0064;&quot; to=&quot;е̄&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0063;&quot; to=&quot;е̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0062;&quot; to=&quot;ӣ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0042;&quot; to=&quot;Ӣ&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0071;&quot; to=&quot;и̃&quot; /&gt;
        ///  &lt;entry from=&quot;&amp;#x0051;&quot; to=&quot;ӣ̃&quot; /&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ThamesM {
            get {
                return ResourceManager.GetString("ThamesM", resourceCulture);
            }
        }
    }
}
